### ISSUE TITLE
Brainstorm

### ISSUE THREAD

**Issue by isombeg** [isombeg/Web-Crawler#1]
- Budget
- Statistics
- Data manipulation
- Geometry

**Comment by shreyall** [comment]
https://medium.com/python-pandemonium/develop-your-first-web-crawler-in-python-scrapy-6b2ee4baf954

**Comment by shreyall** [comment]
https://www.sciencedaily.com/terms/web_crawler.htm

**Comment by isombeg** [comment]
Ideas for Webcrawler:
- E-commerce price comparison
- Weather reports:
   - Looks at different weather reports
   - Rates the reliability of each weather reporter
   - Makes estimations based off of reliability and average of reports
- University programs
- Lender interest rates
- Exchange rates in different parts of the world
